version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app

  front: 
    build:
      dockerfile: EmailUi/Dockerfile
      context: .
    ports:
      - '5173:5173'

